my:
 greeting: HelloToSpringbootConfigApp
 list: 
  values: one,Two,Three
db:
 connection: "{dbconnection:'http:/____', userName:'foo', password:'pass'}"
 host: 127.0.0.1
 port: 1200
server:
 port: 8084

management.endpoints.web.exposure.include: "*"

spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: spring-boot-config

spring.config.import: "optional:configserver:"


